version: "3.2"

services:
  nginx:
    container_name: web-nginx
    build:
      context: ./nginx
      args:
        DOMAIN: ${DOMAIN}
        EMAIL: ${EMAIL}
        FLASK: app
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - app

  app:
    container_name: flask-api
    build: ./${APP_FOLDER}
    command: ["uwsgi", "--ini", "app.ini"]
    environment:
      - FLASK_ENV=${FLASK_ENV}
    ports:
      - 5002:5002
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3